### ISSUE TITLE
Make gutter visibile

### ISSUE THREAD

**Issue by garth** [trevordmiller/nova-atom-syntax#13]
It's nice to see where there getter ends and the code starts. I'm no designer, but the following fixed it for me.

```css
atom-text-editor::shadow .gutter {
  background-color: rgba(0, 0, 0, 0.02);
}
```
