### ISSUE TITLE
Cursor line styling

### ISSUE THREAD

**Issue by garth** [trevordmiller/nova-atom-syntax#14]
Maybe this is personal preference, but I find that the cursor line styling makes the text too faint. So I turned it off.

```css
atom-text-editor::shadow .lines .line.cursor-line {
  background-color: inherit;
}
```
